apiVersion: v1
kind: Service
metadata:
  namespace: archilab
  name: sonarqube-postgres
  labels:
    app: sonarqube
spec:
  ports:
    - name: tcp-postgres
      port: 5432
  type: LoadBalancer
  selector:
    app: sonarqube
