apiVersion: v1
kind: ConfigMap
metadata:
  namespace: archilab
  name: sonarqube-postgres
  labels:
    app: sonarqube
data:
  POSTGRES_DB: sonarqube
  POSTGRES_USER: sonarqube
  POSTGRES_PASSWORD: sonarqube
  PGDATA: /var/lib/postgresql/data/pgdata
