apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: archilab
  name: sonarqube-postgres
  labels:
    app: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  serviceName: sonarqube-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: postgres
          image: postgres:10.11-alpine
          envFrom:
            - configMapRef:
                name: sonarqube-postgres
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -h localhost"]
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -h localhost"]
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: sonarqube
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10G
