apiVersion: v1
kind: ConfigMap
metadata:
  namespace: archilab
  name: sonarqube
  labels:
    app: sonarqube
data:
  SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-postgres.archilab.svc.cluster.local:5432/sonarqube
  SONARQUBE_JDBC_USERNAME: sonarqube
  SONARQUBE_JDBC_PASSWORD: sonarqube
