apiVersion: v1
kind: Service
metadata:
  namespace: archilab
  name: sonarqube
  labels:
    app: sonarqube
spec:
  ports:
    - name: tcp-sonarqube
      port: 9000
  type: LoadBalancer
  selector:
    app: sonarqube
